# Generated by Django 3.1.6 on 2021-04-14 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import faculty.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('email', models.EmailField(default=None, max_length=100)),
                ('department', models.CharField(default=None, max_length=100)),
                ('inst_name', models.CharField(default=None, max_length=100)),
                ('courses', models.TextField(default=None, max_length=100)),
                ('education', models.TextField(default=None, max_length=100)),
                ('pro_int', models.TextField(default=None, max_length=100)),
                ('area_exp', models.TextField(default=None, max_length=100)),
                ('image', models.ImageField(upload_to=faculty.models.PathAndRename('faculty/static/faculty/images'))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
